### ISSUE TITLE
Unable to install HEAD

### ISSUE THREAD

**Issue by patrickfish** [Proxmark/homebrew-proxmark3#10]
Mac OS X 10.12.5
Homebrew 1.2.2-2-gb9cfd2cb5
Homebrew/homebrew-core (git revision fafe3; last commit 2017-06-05)

```
pfish-mbp:~ pfish$  brew install --HEAD proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Updating /Users/pfish/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
==> make clean
==> make all
Last 15 lines from /Users/pfish/Library/Logs/Homebrew/proxmark3/02.make:
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_USE_MACOSX    -c -o lua.o lua.c
gcc -o lua   lua.o liblua.a -lm -lreadline
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_USE_MACOSX    -c -o luac.o luac.c
gcc -o luac   luac.o liblua.a -lm -lreadline
gcc -MT obj/proxmark3.o -MMD -MP -MF obj/proxmark3.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/proxmark3.o proxmark3.c
mv -f obj/proxmark3.Td obj/proxmark3.d
gcc -MT obj/uart.o -MMD -MP -MF obj/uart.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/uart.o uart.c
mv -f obj/uart.Td obj/uart.d
gcc -MT obj/util.o -MMD -MP -MF obj/util.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/util.o util.c
util.c:670:17: error: use of undeclared identifier '_SC_NPROCESSORS_ONLN'
        return sysconf(_SC_NPROCESSORS_ONLN);
                       ^
1 error generated.
make[1]: *** [obj/util.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

pfish-mbp:~ pfish$
```

**Comment by patrickfish** [comment]
Log attached

[02.make.txt](https://github.com/Proxmark/homebrew-proxmark3/files/1052972/02.make.txt)

**Comment by marshmellow42** [comment]
hmmm  _SC_NPROCESSORS_ONLN should be supported by osx.

@pwpiwi could it be related to the last post at http://cvs-ghc.haskell.narkive.com/F8LSIKKn/head-does-not-validate-on-os-x  ?

**Comment by marshmellow42** [comment]
we do have _POSIX_C_SOURCE defined at client/util.c line 12  

so it is possible the issue is similar to the link i sent above.

**Comment by pwpiwi** [comment]
Yes, you probably nailed it down. Problem is that we need _POSIX_C_SOURCE for the nanoseconds timer. So we are back to a separate source file for the timer only...

**Comment by pwpiwi** [comment]
Possible fix pushed to HEAD. Please give it a try and provide some feedback.

**Comment by patrickfish** [comment]
Got a little further this time...ran into this:

```
gcc -MT obj/hardnested/hardnested_bruteforce.o -MMD -MP -MF obj/hardnested/hardnested_bruteforce.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/hardnested/hardnested_bruteforce.o hardnested/hardnested_bruteforce.c
hardnested/hardnested_bruteforce.c:57:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
make[1]: *** [obj/hardnested/hardnested_bruteforce.o] Error 1
```

I modified client/Makefile to include "-I /usr/include/malloc" which fixed that, but possibly caused this:

```
g++  obj/proxmark3.o obj/uart.o obj/util.o obj/util_posix.o obj/crapto1/crapto1.o obj/crapto1/crypto1.o obj/mfkey.o obj/loclass/cipher.o obj/loclass/cipherutils.o obj/loclass/des.o obj/loclass/ikeys.o obj/loclass/elite_crack.o obj/loclass/fileutils.o obj/whereami.o obj/mifarehost.o obj/parity.o obj/crc.o obj/crc16.o obj/crc64.o obj/iso14443crc.o obj/iso15693tools.o obj/data.o obj/graph.o obj/ui.o obj/cmddata.o obj/lfdemod.o obj/cmdhf.o obj/cmdhf14a.o obj/cmdhf14b.o obj/cmdhf15.o obj/cmdhfepa.o obj/cmdhflegic.o obj/cmdhficlass.o obj/cmdhfmf.o obj/cmdhfmfu.o obj/cmdhfmfhard.o obj/hardnested/hardnested_bruteforce.o obj/cmdhftopaz.o obj/cmdhw.o obj/cmdlf.o obj/cmdlfawid.o obj/cmdlfcotag.o obj/cmdlfem4x.o obj/cmdlffdx.o obj/cmdlfgproxii.o obj/cmdlfhid.o obj/cmdlfhitag.o obj/cmdlfio.o obj/cmdlfindala.o obj/cmdlfjablotron.o obj/cmdlfnexwatc


h.o obj/cmdlfnoralsy.o obj/cmdlfparadox.o obj/cmdlfpcf7931.o obj/cmdlfpresco.o obj/cmdlfpyramid.o obj/cmdlfsecurakey.o obj/cmdlft55xx.o obj/cmdlfti.o obj/cmdlfviking.o obj/cmdlfvisa2000.o obj/cmdparser.o obj/cmdmain.o obj/scripting.o obj/cmdscript.o obj/pm3_binlib.o obj/pm3_bitlib.o obj/aes.o obj/protocols.o obj/sha1.o obj/cmdcrc.o obj/reveng/reveng.o obj/reveng/cli.o obj/reveng/bmpbit.o obj/reveng/model.o obj/reveng/poly.o obj/reveng/getopt.o obj/proxgui.o obj/proxguiqt.o obj/proxguiqt.moc.o obj/hardnested/hardnested_bf_core_NOSIMD.o obj/hardnested/hardnested_bitarray_core_NOSIMD.o obj/hardnested/hardnested_bf_core_MMX.o obj/hardnested/hardnested_bitarray_core_MMX.o obj/hardnested/hardnested_bf_core_SSE2.o obj/hardnested/hardnested_bitarray_core_SSE2.o obj/hardnested/hardnested_bf_core_AVX.o obj/hardnested/hardnested_bitarray_core_AVX.o obj/hardnested/hardnested_bf_core_AVX2.o obj/hardnested/hardnested_bitarray_core_AVX2.o -L/opt/local/lib -L/usr/local/lib -lreadline -lpthread -lm ../liblua/liblua.a -F/usr/local/Cellar/qt/5.9.0/lib -framework QtWidgets -F/usr/local/Cellar/qt/5.9.0/lib -framework QtGui -F/usr/local/Cellar/qt/5.9.0/lib -framework QtCore -o proxmark3
Undefined symbols for architecture x86_64:
  "_memalign", referenced from:
      _crack_states_bitsliced_NOSIMD in hardnested_bf_core_NOSIMD.o
      _malloc_bitarray_NOSIMD in hardnested_bitarray_core_NOSIMD.o
      _crack_states_bitsliced_MMX in hardnested_bf_core_MMX.o
      _malloc_bitarray_MMX in hardnested_bitarray_core_MMX.o
      _crack_states_bitsliced_SSE2 in hardnested_bf_core_SSE2.o
      _malloc_bitarray_SSE2 in hardnested_bitarray_core_SSE2.o
      _crack_states_bitsliced_AVX in hardnested_bf_core_AVX.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [proxmark3] Error 1
bash-3.2$
```

**Comment by marshmellow42** [comment]
what if you replace <malloc.h> with <stdlib.h>?

**Comment by marshmellow42** [comment]
the second issue looks more involved :(

**Comment by patrickfish** [comment]
Looks like stdlib.h is already defined there, but I removed malloc.h and it results in the same error.

**Comment by marshmellow42** [comment]
i confirmed removing <malloc.h> and replacing it with <stdlib.h> works on osx 10.12  
you have to remove it in 3 files though (all in the hardnested folder).
i have a test env setup and can test further on the other issue tomorrow...  (unless piwi beats me to it.)

**Comment by pwpiwi** [comment]
The issue is with the `memalign()` function. MacOS has `posix_memalign()` instead. I have created another pull request (not yet merged) which should hopefully fix the issue.

**Comment by pwpiwi** [comment]
Fix is available now in --HEAD. Please test.

**Comment by patrickfish** [comment]
Tested and was able to compile and connect to a device. Thank you very much @pwpiwi!
